// <auto-generated />
namespace ITI.UI40Smart.MVC.Day02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uniqueemailfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniqueemailfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202005051338364_unique email field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
